server:
  port: 44002

spring:
  application:
    name: seata-api
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seata_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      maximum-pool-size: 5
  jpa:
    show-sql: true
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:19000/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: 127.0.0.1:${server.port}
    # 间隔多少秒发送一次心跳包给eureka
    lease-renewal-interval-in-seconds: 1
    # 允许的超时秒数，超时即使eureka认为该服务已停掉
    lease-expiration-duration-in-seconds: 180

feign:
  hystrix:
    enabled: false

registry:
  type: eureka
service:
  vgroupMapping:
    my_test_tx_group: "default"
