server:
  port: 19001

dubbo:
  application:
    # 服务名称，保持唯一
    name: dubbo-customer
    # zookeeper地址，用于向其注册服务
  registry:
    address: zookeeper://127.0.0.1:2181
  #暴露服务方式
  protocol:
    # dubbo协议，固定写法
    name: dubbo
    serialization: kryo
    optimizer: com.blysin.config.SerializationOptimizerImpl
  monitor:
    protocol: registry
